# Generated by Django 4.0.4 on 2022-06-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreriaWeb', '0002_cliente_comuna_region_seguimiento_compra_subcripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imgen',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
